# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-27 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=200)),
                ('behaviour', models.CharField(max_length=50)),
                ('class_position', models.IntegerField()),
                ('achievements', models.CharField(max_length=50)),
                ('comments', models.TextField(max_length=200)),
                ('announcement', models.TextField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
