# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-27 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continuous_Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=200, null=True)),
                ('Test_name', models.CharField(max_length=50)),
                ('Test_mark', models.IntegerField(null=True)),
            ],
        ),
    ]
